"""
AlphaForge | Performance & Factor Attribution
Fama-French style factor decomposition and cumulative active alpha generation.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from helper import inject_custom_theme
from sidebar import render_sidebar, get_or_run_quant_results

st.set_page_config(page_title="AlphaForge - Factor Attribution", page_icon="🧩", layout="wide")
inject_custom_theme()

# Render Unified Sidebar
ticker, company, exchange, period, interval, region = render_sidebar()

# Fetch active quantitative factor results
results = get_or_run_quant_results()
mean_attrib = results["attrib_summary"]
ts_attrib = results["cum_attribution"]
benchmark_name = results.get("benchmark_name", "Nifty 50" if region == "India" else "S&P 500")

st.markdown(f"# 🧩 Performance & Factor Attribution — {region.upper()}")
st.caption(
    f"Decomposing portfolio active performance against systematic factor-mimicking portfolios and "
    f"the **{benchmark_name}** benchmark."
)

st.subheader("📊 Average Daily & Annualized Factor Alpha Attribution")
st.markdown(r"""
We map active weights against **Fama-French style long-short factor portfolios**:
- **Momentum**: Top decile minus Bottom decile securities ranked by 12–1 month return.
- **Low Volatility**: Top decile minus Bottom decile securities ranked by Low Volatility.
- **Fundamental Value**: Top decile minus Bottom decile securities ranked by Inverse P/E & Dividend Yield.
- **Quality**: Top decile minus Bottom decile securities ranked by YoY EPS Growth.

The active return contribution for factor $f$ is evaluated as:

$$
\mathrm{Contribution}_f
=
\beta_{\mathrm{active},\,f}
\cdot
\mathrm{Factor\ Return}_f
$$
""")

# Attribution Table
attrib_display = mean_attrib.copy()
st.dataframe(
    attrib_display.style.format({
        "Contribution": "{:.4%}",
        "Annualized Contribution": "{:+.2%}"
    }).background_gradient(subset=["Annualized Contribution"], cmap="RdYlGn"),
    width="stretch"
)

st.divider()

# Alpha Decomposition Bar Chart
st.subheader("🧩 Annualized Factor Tilt Decomposition")
st.markdown("Net annualized returns generated by intentional factor tilts vs. market and residual returns:")

factor_names = ["Momentum", "Volatility", "Value", "Quality", "Market", "Residual"]
valid_names = [f for f in factor_names if f in attrib_display.index]
factor_contribs = [attrib_display.loc[f, "Annualized Contribution"] for f in valid_names]

fig_bar = px.bar(
    x=valid_names,
    y=factor_contribs,
    labels=dict(x="Factor Component", y="Annualized Return Contribution"),
    title=f"Factor Return Contribution ({region})",
    color=factor_contribs,
    color_continuous_scale="RdYlGn",
    text_auto=".2%"
)
fig_bar.update_layout(
    plot_bgcolor="#161B22",
    paper_bgcolor="#0E1117",
    font_color="#FFFFFF",
    yaxis=dict(tickformat=".1%", showgrid=True, gridcolor="#21262D"),
    xaxis=dict(showgrid=False)
)
st.plotly_chart(fig_bar, width="stretch")

st.divider()

# Cumulative Factor Return Timeseries Chart
st.subheader("📈 Cumulative Factor Return Decomposition")
st.markdown("Timeseries displaying how each intentional factor exposure accumulated alpha over the backtest horizon:")

fig_ts = go.Figure()

colors = {
    "Momentum": "#00C8FF",
    "Volatility": "#FFD700",
    "Value": "#00E676",
    "Quality": "#FF6B8B",
    "Market": "#94A3B8",
    "Residual": "#A855F7"
}

for col in ["Momentum", "Volatility", "Value", "Quality"]:
    if col in ts_attrib.columns:
        fig_ts.add_trace(go.Scatter(
            x=ts_attrib.index,
            y=ts_attrib[col],
            mode="lines",
            name=f"{col} Factor",
            line=dict(color=colors.get(col, "#FFFFFF"), width=2)
        ))

fig_ts.update_layout(
    title="Cumulative Factor Alpha Timeseries",
    xaxis_title="Date",
    yaxis_title="Cumulative Return Contribution",
    plot_bgcolor="#161B22",
    paper_bgcolor="#0E1117",
    font_color="#FFFFFF",
    xaxis=dict(showgrid=True, gridcolor="#21262D"),
    yaxis=dict(showgrid=True, gridcolor="#21262D", tickformat=".1%"),
    legend=dict(x=0.02, y=0.98, bgcolor="rgba(0,0,0,0.5)")
)
st.plotly_chart(fig_ts, width="stretch")
